name: TeamsSimplifiedDynmapExtension
author: Destinyofyeet
version: 0.0.2
main: me.destinyofyeet.TeamsSimplifiedDynmapExtension.main.Main
website: https://github.com/DestinyofYeet/
api-version: 1.17

softdepend:
  - dynmap
  - TeamsSimplified